// <auto-generated />

#nullable disable

using Infrastructure.DbConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Infrastructure.Migrations.Etl
{
    [DbContext(typeof(EtlDbContext))]
    [Migration("20250902115450_TriadAndSchemaRefactor")]
    partial class TriadAndSchemaRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("etl_backend.Domain.Entities.DataTableColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("string");

                    b.Property<int>("DataTableSchemaId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalColumnName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataTableSchemaId", "ColumnName")
                        .IsUnique();

                    b.ToTable("DataTableColumns");
                });

            modelBuilder.Entity("etl_backend.Domain.Entities.DataTableSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("DataTableSchemas");
                });

            modelBuilder.Entity("etl_backend.Domain.Entities.StagedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SchemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("SchemaId")
                        .IsUnique();

                    b.HasIndex("StoredFilePath")
                        .IsUnique();

                    b.HasIndex("UploadedAt");

                    b.HasIndex("Stage", "Status");

                    b.ToTable("staged_files", (string)null);
                });

            modelBuilder.Entity("etl_backend.Domain.Entities.DataTableColumn", b =>
                {
                    b.HasOne("etl_backend.Domain.Entities.DataTableSchema", "DataTable")
                        .WithMany("Columns")
                        .HasForeignKey("DataTableSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTable");
                });

            modelBuilder.Entity("etl_backend.Domain.Entities.StagedFile", b =>
                {
                    b.HasOne("etl_backend.Domain.Entities.DataTableSchema", "Schema")
                        .WithOne()
                        .HasForeignKey("etl_backend.Domain.Entities.StagedFile", "SchemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("etl_backend.Domain.Entities.DataTableSchema", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
