name: Docker Image CI Test

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dani-docker.ir
          username: admin
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build frontend image
        run: docker build -f etl_frontend/Dockerfile -t registry.dockerize.ir/etlteam3/frontend_$(date +%Y%m%d%H%M%S) ./frontend

      - name: Push frontend image
        run: docker push registry.dockerize.ir/etlteam3/frontend:$(date +%Y%m%d%H%M%S)
      #        run: docker push registry.dockerize.ir/etl_team3/frontend:$(date +%Y%m%d%H%M%S)

      - name: Build backend image
        run: docker build -f etl_backend/WebApi/Dockerfile -t registry.dockerize.ir/etlteam3/backend_$(date +%Y%m%d%H%M%S) ./backend

      - name: Push backend image
        run: docker push registry.dockerize.ir/etlteam3/backend:$(date +%Y%m%d%H%M%S)
#        run: docker push registry.dockerize.ir/etl_team3/backend:$(date +%Y%m%d%H%M%S)
